In [7]:
import pandas as pd
import numpy as np
import seaborn as sns

In [8]:
cc_df = pd.read_csv('fraud.csv')

In [9]:
pd.set_option('display.max_columns', 50)

In [10]:
cc_df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
1,2019-01-01 00:12:34,4956828990005111019,"fraud_Schultz, Simonis and Little",grocery_pos,44.71,Kenneth,Robinson,M,269 Sanchez Rapids,Elizabeth,NJ,7208,40.6747,-74.2239,124967,Operational researcher,1980-12-21,09eff9c806365e2a6be12c1bbab3d70e,1325376754,40.079588,-74.848087,0
2,2019-01-01 00:17:16,180048185037117,fraud_Kling-Grant,grocery_net,46.28,Mary,Wall,F,2481 Mills Lock,Plainfield,NJ,7060,40.6152,-74.4150,71485,Leisure centre manager,1974-07-19,19e23c6a300c774354417befe4f31f8c,1325377036,40.021888,-74.228188,0
3,2019-01-01 00:20:15,374930071163758,fraud_Deckow-O'Conner,grocery_pos,64.09,Daniel,Escobar,M,61390 Hayes Port,Romulus,MI,48174,42.2203,-83.3583,31515,Police officer,1971-11-05,6f363661ba6b55889e488dd178f2a0af,1325377215,42.360426,-83.552316,0
4,2019-01-01 00:23:41,2712209726293386,fraud_Balistreri-Nader,misc_pos,25.58,Jenna,Brooks,F,50872 Alex Plain Suite 088,Baton Rouge,LA,70808,30.4066,-91.1468,378909,"Designer, furniture",1977-02-22,1654da2abfb9e79a5f99167fc9779558,1325377421,29.737426,-90.853194,0

In [11]:
cc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491134 entries, 0 to 491133
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  491134 non-null  object
 1   cc_num                 491134 non-null  int64
 2   merchant               491134 non-null  object
 3   category               491134 non-null  object
 4   amt                    491134 non-null  float64
 5   first                  491134 non-null  object
 6   last                   491134 non-null  object
 7   gender                 491134 non-null  object
 8   street                 491134 non-null  object
 9   city                   491134 non-null  object
 10  state                  491134 non-null  object
 11  zip                    491134 non-null  int64
 12  lat                    491134 non-null  float64
 13  long                   491134 non-null  float64
 14  city_pop               491134 non-null  int64
 15  job                    491134 non-null  object
 16  dob                    491134 non-null  object
 17  trans_num              491134 non-null  object
 18  unix_time              491134 non-null  int64
 19  merch_lat              491134 non-null  float64
 20  merch_long             491134 non-null  float64
 21  is_fraud               491134 non-null  int64
dtypes: float64(5), int64(5), object(12)
memory usage: 82.4+ MB

In [12]:
cc_df.describe()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,4.911340e+05,491134.000000,491134.000000,491134.000000,491134.000000,4.911340e+05,4.911340e+05,491134.000000,491134.000000,491134.000000
mean,3.706013e+17,69.050120,50770.532384,37.931230,-90.495619,1.213922e+05,1.358730e+09,37.930272,-90.495411,0.002533
std,1.260229e+18,160.322867,26854.947965,5.341193,12.990732,3.725751e+05,1.819402e+07,5.372986,13.004100,0.050264
min,5.038744e+11,1.000000,1843.000000,24.655700,-122.345600,4.600000e+01,1.325376e+09,23.655789,-123.345106,0.000000
25%,2.131124e+14,8.960000,28405.000000,33.746700,-97.235100,1.228000e+03,1.343087e+09,33.781388,-96.984814,0.000000
50%,3.531130e+15,42.170000,49628.000000,38.507200,-87.591700,5.760000e+03,1.357257e+09,38.545124,-87.573441,0.000000
75%,4.653879e+15,80.330000,75048.000000,41.520500,-80.731000,5.083500e+04,1.374626e+09,41.624294,-80.685567,0.000000
max,4.956829e+18,25086.940000,99323.000000,48.887800,-69.965600,2.906700e+06,1.388534e+09,49.887523,-68.965624,1.000000

In [13]:
cc_df.head(3)

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
1,2019-01-01 00:12:34,4956828990005111019,"fraud_Schultz, Simonis and Little",grocery_pos,44.71,Kenneth,Robinson,M,269 Sanchez Rapids,Elizabeth,NJ,7208,40.6747,-74.2239,124967,Operational researcher,1980-12-21,09eff9c806365e2a6be12c1bbab3d70e,1325376754,40.079588,-74.848087,0
2,2019-01-01 00:17:16,180048185037117,fraud_Kling-Grant,grocery_net,46.28,Mary,Wall,F,2481 Mills Lock,Plainfield,NJ,7060,40.6152,-74.4150,71485,Leisure centre manager,1974-07-19,19e23c6a300c774354417befe4f31f8c,1325377036,40.021888,-74.228188,0

In [14]:
cc_df['merchant'].nunique()

693

In [15]:
cc_df['job'].nunique()

110

In [16]:
cc_df.drop(['merchant','first','last','street','city','state','zip','job','trans_num','unix_time'], axis = 1, inplace= True)

In [17]:
cc_df.sort_values('cc_num') # sort_values(): 특정 컬럼 기준 정렬 / 'cc_num': 카드 번호 컬럼 선택

,trans_date_trans_time,cc_num,category,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud
378075,2020-08-05 17:03:19,503874407318,shopping_pos,7.77,M,29.5894,-98.5201,1595797,1975-12-28,30.014539,-98.426767,0
230588,2019-12-20 22:21:36,503874407318,health_fitness,72.06,M,29.5894,-98.5201,1595797,1975-12-28,29.260487,-97.961746,0
421413,2020-10-10 12:39:32,503874407318,misc_pos,4.78,M,29.5894,-98.5201,1595797,1975-12-28,29.116928,-99.258936,0
468378,2020-12-13 15:55:44,503874407318,kids_pets,84.56,M,29.5894,-98.5201,1595797,1975-12-28,29.994537,-98.441297,0
345085,2020-06-22 23:52:06,503874407318,entertainment,24.33,M,29.5894,-98.5201,1595797,1975-12-28,29.277168,-98.239289,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53631,2019-04-14 16:57:31,4956828990005111019,entertainment,27.41,M,40.6747,-74.2239,124967,1980-12-21,39.888460,-74.151440,0
485223,2020-12-27 14:14:40,4956828990005111019,home,28.52,M,40.6747,-74.2239,124967,1980-12-21,41.068207,-75.015316,0
264968,2020-02-15 13:32:48,4956828990005111019,shopping_pos,2.95,M,40.6747,-74.2239,124967,1980-12-21,41.435438,-73.839008,0
63475,2019-04-30 17:45:09,4956828990005111019,shopping_pos,7.28,M,40.6747,-74.2239,124967,1980-12-21,41.149072,-75.143152,0
450904,2020-11-28 12:12:27,4956828990005111019,food_dining,16.22,M,40.6747,-74.2239,124967,1980-12-21,39.933227,-73.659492,0

In [18]:
temp = pd.DataFrame({'a': [10,20,30,20,10,200], 'b': [100,300,200,150,250,200], 'c': [10, 500, 20, 250, 25, 200]})
# pd.DataFrame(): 데이터프레임 생성
# 각 컬럼(a, b, c)에 리스트 형태로 값 입력하여 구조 생성

In [19]:
temp

     a    b    c
0   10  100   10
1   20  300  500
2   30  200   20
3   20  150  250
4   10  250   25
5  200  200  200

In [20]:
temp.mean()

a     48.333333
b    200.000000
c    167.500000
dtype: float64

In [21]:
temp.std()

a     74.677083
b     70.710678
c    192.503247
dtype: float64

In [22]:
(temp['a'] - 48.33) / 74.67 # (값 - 평균) / 표준편차 계산식 적용

0   -0.513325
1   -0.379403
2   -0.245480
3   -0.379403
4   -0.513325
5    2.031204
Name: a, dtype: float64

In [23]:
(temp['b'] - temp['b'].mean()) / temp['b'].std() # (값 - 평균) / 표준편차 계산식 적용

0   -1.414214
1    1.414214
2    0.000000
3   -0.707107
4    0.707107
5    0.000000
Name: b, dtype: float64

In [24]:
(temp['c'] - temp['c'].mean()) / temp['c'].std() # (값 - 평균) / 표준편차 계산식 적용

0   -0.818168
1    1.727244
2   -0.766221
3    0.428564
4   -0.740247
5    0.168828
Name: c, dtype: float64

In [25]:
cc_df['cc_num'].value_counts()

cc_num
6538441737335434    4392
30270432095985      4392
4364010865167176    4386
4642255475285942    4386
6538891242532018    4386
                    ...
36913587729122      3641
4681601008538160    3638
30551643947183      3638
4005676619255478    3638
3511378610369890    3628
Name: count, Length: 124, dtype: int64

In [26]:
amt_info = cc_df.groupby('cc_num')['amt'].agg(['mean','std']).reset_index()
# groupby('cc_num'): cc_num 기준으로 그룹화
# ['amt']: 거래 금액 컬럼 선택
# agg(['mean','std']): 평균과 표준편차 계산
# reset_index(): 그룹화 결과를 데이터프레임 형태로 재정렬

In [27]:
amt_info.to_pickle('./amt_info.pkl') # to_pickle(): 객체를 피클 형식으로 저장

In [28]:
cc_df = cc_df.merge(amt_info, on='cc_num', how='left') # merge(): 두 데이터프레임 결합 / on='cc_num': 기준 컬럼 / how='left': 왼쪽 기준 병합

In [29]:
cc_df['amt_z'] = (cc_df['amt'] - cc_df['mean']) / cc_df['std'] # (값 - 평균) / 표준편차 계산식을 적용하여 z-score 생성

In [30]:
cc_df[cc_df['is_fraud'] == 1] # is_fraud가 1인 행만 필터링하여 조회

,trans_date_trans_time,cc_num,category,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,mean,std,amt_z
4794,2019-01-12 00:59:01,581686439828,gas_transport,11.73,M,41.5205,-80.0573,5507,1973-07-28,41.947427,-79.796264,1,58.578675,149.804992,-0.312731
4816,2019-01-12 03:48:07,581686439828,grocery_pos,328.68,M,41.5205,-80.0573,5507,1973-07-28,42.148618,-79.398595,1,58.578675,149.804992,1.803020
4979,2019-01-12 15:46:10,581686439828,food_dining,120.58,M,41.5205,-80.0573,5507,1973-07-28,42.470024,-80.126576,1,58.578675,149.804992,0.413880
5073,2019-01-12 19:53:59,581686439828,shopping_net,1081.35,M,41.5205,-80.0573,5507,1973-07-28,42.455406,-79.521640,1,58.578675,149.804992,6.827351
5124,2019-01-12 22:44:05,581686439828,shopping_net,776.70,M,41.5205,-80.0573,5507,1973-07-28,40.680209,-79.099101,1,58.578675,149.804992,4.793708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477832,2020-12-21 02:21:41,4716561796955522,grocery_pos,358.24,F,48.2777,-112.8456,743,1972-05-04,47.526202,-113.643313,1,52.537867,106.113023,2.880911
477847,2020-12-21 02:36:03,4716561796955522,shopping_net,859.12,F,48.2777,-112.8456,743,1972-05-04,48.272348,-112.328075,1,52.537867,106.113023,7.601161
479296,2020-12-21 22:38:38,4716561796955522,home,209.84,F,48.2777,-112.8456,743,1972-05-04,49.173669,-112.698767,1,52.537867,106.113023,1.482402
479305,2020-12-21 22:42:11,4716561796955522,food_dining,123.58,F,48.2777,-112.8456,743,1972-05-04,48.913048,-113.214921,1,52.537867,106.113023,0.669495
479341,2020-12-21 22:59:22,4716561796955522,home,219.11,F,48.2777,-112.8456,743,1972-05-04,47.911219,-113.691603,1,52.537867,106.113023,1.569761

In [31]:
cc_df.drop(['mean','std'], axis = 1, inplace = True)  # drop(): 컬럼 제거 / axis=1: 컬럼 방향 / inplace=True: 원본에 적용

In [32]:
cat_info = cc_df.groupby(['cc_num','category'])['amt'].agg(['mean','std']).reset_index()
# groupby(['cc_num','category']): 두 컬럼 기준 그룹화
# ['amt']: 결제 금액 컬럼 선택
# agg(['mean','std']): 각 그룹의 평균, 표준편차 계산
# reset_index(): 그룹 결과를 데이터프레임 형태로 재정렬

In [33]:
cat_info.to_pickle('./cat_info.pkl') # to_pickle(): 객체를 피클 파일로 저장

In [34]:
cc_df = cc_df.merge(cat_info, on='cc_num', how='left')
# cc_df = cc_df.merge(cat_info, on=['cc_num','category'], how='left')
# 두 컬럼(cc_num, category)erge(): 데이터프레임 결합 / on='cc_num': 기준  기준 병합으로 정상 정렬됨  # m컬럼 / how='left': 왼쪽 기준 병합

In [35]:
cc_df['cat_amt_z'] = (cc_df['amt'] - cc_df['mean']) / cc_df['std'] # (값 - 평균) / 표준편차 계산식을 적용하여 z-score 생성

In [36]:
cc_df.drop(['mean','std'], axis =1 , inplace = True)  # drop(): 컬럼 제거 / axis=1: 컬럼 방향 / inplace=True: 원본에 적용

In [37]:
cc_df.head()

,trans_date_trans_time,cc_num,category_x,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,amt_z,category_y,cat_amt_z
0,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,entertainment,1.021883
1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,food_dining,2.048113
2,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,gas_transport,3.110189
3,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_net,2.722909
4,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_pos,0.317631

In [38]:
cc_df['hour'] = pd.to_datetime(cc_df['trans_date_trans_time']).dt.hour # datetime 변환 후 .dt.hour로 시(hour)만 추출

In [39]:
cc_df.head()

,trans_date_trans_time,cc_num,category_x,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,amt_z,category_y,cat_amt_z,hour
0,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,entertainment,1.021883,0
1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,food_dining,2.048113,0
2,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,gas_transport,3.110189,0
3,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_net,2.722909,0
4,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_pos,0.317631,0

In [40]:
def hour_func(x):
    if (x >= 6) & (x < 12):
        return 'morning'       # 6시~11시
    elif (x >= 12) & (x < 18):
        return 'afternoon'     # 12시~17시
    elif (x >= 18) & (x < 23):
        return 'night'         # 18시~22시
    else:
        return 'evening'       # 그 외 시간대

In [41]:
cc_df['hour_cat'] = cc_df['hour'].apply(hour_func)  # apply(): 각 값에 함수 적용하여 시간대 범주 생성

In [42]:
cc_df.head()

,trans_date_trans_time,cc_num,category_x,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,amt_z,category_y,cat_amt_z,hour,hour_cat
0,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,entertainment,1.021883,0,evening
1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,food_dining,2.048113,0,evening
2,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,gas_transport,3.110189,0,evening
3,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_net,2.722909,0,evening
4,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_pos,0.317631,0,evening

In [43]:
cc_df['hour_cat'].value_counts()

hour_cat
afternoon    2475214
night        2053758
evening      1381268
morning       965636
Name: count, dtype: int64

In [44]:
all_cnt = cc_df.groupby('cc_num')['amt'].count().reset_index()  # count(): 각 그룹의 데이터 개수 계산

In [45]:
hour_cnt = cc_df.groupby(['cc_num','hour_cat'])['amt'].count().reset_index() # 두 컬럼 기준 그룹화하여 개수 계산

In [46]:
all_cnt.head()

         cc_num    amt
0  503874407318  51170
1  567868110212  51016
2  571365235126  61236
3  581686439828  51142
4  630423337322  61068

In [47]:
hour_cnt.head()

         cc_num   hour_cat    amt
0  503874407318  afternoon  17920
1  503874407318    evening  10318
2  503874407318    morning   7812
3  503874407318      night  15120
4  567868110212  afternoon  17192

In [48]:
hour_cnt = hour_cnt.merge(all_cnt, on='cc_num', how='left')

In [49]:
hour_cnt.head()

         cc_num   hour_cat  amt_x  amt_y
0  503874407318  afternoon  17920  51170
1  503874407318    evening  10318  51170
2  503874407318    morning   7812  51170
3  503874407318      night  15120  51170
4  567868110212  afternoon  17192  51016

In [50]:
hour_cnt = hour_cnt.rename(columns={'amt_x': 'hour_cnt', 'amt_y': 'total_cnt'}) # rename(): 컬럼명 변경

In [51]:
hour_cnt.head()

         cc_num   hour_cat  hour_cnt  total_cnt
0  503874407318  afternoon     17920      51170
1  503874407318    evening     10318      51170
2  503874407318    morning      7812      51170
3  503874407318      night     15120      51170
4  567868110212  afternoon     17192      51016

In [52]:
hour_cnt['hour_perc'] = hour_cnt['hour_cnt'] / hour_cnt['total_cnt']  # 특정 시간대 비율 계산

In [53]:
hour_cnt.head(10)

         cc_num   hour_cat  hour_cnt  total_cnt  hour_perc
0  503874407318  afternoon     17920      51170   0.350205
1  503874407318    evening     10318      51170   0.201642
2  503874407318    morning      7812      51170   0.152668
3  503874407318      night     15120      51170   0.295486
4  567868110212  afternoon     17192      51016   0.336992
5  567868110212    evening     11480      51016   0.225027
6  567868110212    morning      7406      51016   0.145170
7  567868110212      night     14938      51016   0.292810
8  571365235126  afternoon     21322      61236   0.348194
9  571365235126    evening     13202      61236   0.215592

In [54]:
hour_cnt.tail(10)

                  cc_num   hour_cat  hour_cnt  total_cnt  hour_perc
486  4861310130652566408    morning      7406      51002   0.145210
487  4861310130652566408      night     14462      51002   0.283558
488  4906628655840914250  afternoon     17948      51170   0.350752
489  4906628655840914250    evening     11200      51170   0.218878
490  4906628655840914250    morning      7000      51170   0.136799
491  4906628655840914250      night     15022      51170   0.293570
492  4956828990005111019  afternoon     17878      51198   0.349193
493  4956828990005111019    evening     10976      51198   0.214383
494  4956828990005111019    morning      7812      51198   0.152584
495  4956828990005111019      night     14532      51198   0.283839

In [55]:
cc_df.head()

,trans_date_trans_time,cc_num,category_x,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,amt_z,category_y,cat_amt_z,hour,hour_cat
0,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,entertainment,1.021883,0,evening
1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,food_dining,2.048113,0,evening
2,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,gas_transport,3.110189,0,evening
3,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_net,2.722909,0,evening
4,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_pos,0.317631,0,evening

In [56]:
hour_cnt = hour_cnt[['cc_num','hour_cat','hour_perc']]  # 특정 컬럼만 남겨 새로운 데이터프레임 구성

In [57]:
hour_cnt.to_pickle('./hour_cnt.pkl')  # to_pickle(): 객체를 피클 형식으로 저장

In [58]:
cc_df = cc_df.merge(hour_cnt, on=['cc_num','hour_cat'], how='left')  # 두 컬럼 기준 left merge 수행

In [59]:
cc_df.head()

,trans_date_trans_time,cc_num,category_x,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,amt_z,category_y,cat_amt_z,hour,hour_cat,hour_perc
0,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,entertainment,1.021883,0,evening,0.19647
1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,food_dining,2.048113,0,evening,0.19647
2,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,gas_transport,3.110189,0,evening,0.19647
3,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_net,2.722909,0,evening,0.19647
4,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,0.321302,grocery_pos,0.317631,0,evening,0.19647

In [60]:
cc_df.drop(['trans_date_trans_time', 'hour', 'hour_cat'], axis =1 , inplace = True)  # axis=1: 컬럼 방향 / inplace=True: 원본에 적용

In [61]:
!pip install geopy

'pip'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

In [62]:
from geopy.distance import distance

In [65]:
distance((48.8878, -118.2105), (49.159047, -118.186462)).km

30.216618410409005

In [ ]:
cc_df['distance'] = cc_df.apply(lambda x: distance((x['lat'], x['long']), (x['merch_lat'], x['merch_long'])).km, axis = 1)  # 각 행에 대해 거리 계산 수행

In [ ]:
from datetime import datetime

In [ ]:
start_time =  datetime.now()
cc_df.head(10000).apply(lambda x: distance((x['lat'], x['long']), (x['merch_lat'], x['merch_long'])).km, axis = 1)
datetime.now() - start_time

In [ ]:
cc_df.head()

In [ ]:
dist_info = cc_df.groupby('cc_num')['distance'].agg(['mean','std']).reset_index()  # 그룹별 거리 통계 계산

In [ ]:
dist_info.to_pickle('./dist_info.pkl')  # 거리 통계 정보를 피클로 저장

In [ ]:
cc_df = cc_df.merge(dist_info, on='cc_num', how='left')  # 거리 통계 정보 결합 (row 수 증가 여부 확인 권장)

In [ ]:
cc_df.head()

In [ ]:
cc_df['dist_z'] = (cc_df['distance'] - cc_df['mean']) / cc_df['std']  # (값 - 평균) / 표준편차 계산하여 거리 z-score 생성

In [ ]:
cc_df

In [ ]:
cc_df.drop(['lat','long','merch_lat','merch_long','mean','std'], axis = 1, inplace = True)
# drop(): 특정 컬럼 제거
# ['lat','long','merch_lat','merch_long']: 고객/상점의 위도·경도 컬럼
# ['mean','std']: 이전 단계에서 z-score 계산 후 불필요해진 컬럼
# axis=1: 컬럼 방향 제거
# inplace=True: cc_df 원본에 직접 적용하여 수정

In [ ]:
cc_df['dob'] = pd.to_datetime(cc_df['dob']).dt.year
# pd.to_datetime(): dob 문자열을 datetime 형태로 변환
# .dt.year: 날짜에서 연도(year) 부분만 추출
# 추출한 연도를 dob 컬럼에 다시 저장하여 생년 정보만 남김

In [ ]:
#cc_df['category'].nunique()
cc_df['category']

In [ ]:
# cat_info merge 과정에서 category 컬럼이 category_x, category_y로 나뉜 상태를 정리
# 원래 cc_df에 있던 거래별 category 정보는 category_x에 있으므로 이를 기준으로 최종 category 컬럼을 복원합니다.
cc_df['category'] = cc_df['category_x']  # category_x를 최종 category로 사용하여 본래 카테고리 값 유지
cc_df.drop(['category_x', 'category_y'], axis=1, inplace=True)  # 더 이상 필요 없는 임시 컬럼(category_x, category_y) 제거

# 범주형 컬럼 'category'에 몇 종류의 값이 있는지 확인
cc_df['category'].nunique()  # 고유한 결제 카테고리(범주) 개수 확인

In [ ]:
cc_df = pd.get_dummies(cc_df, drop_first=True)

In [ ]:
cc_df.head()

In [ ]:
cc_df.drop('cc_num', axis = 1, inplace = True)